###############################################################################
# NAME:		    Makefile
#
# AUTHOR:	    Ethan D. Twardy
#
# DESCRIPTION:	    Makefile for the constituent files with make up the `bits'
#		    utilities.
#
# CREATED:	    05/11/2018
#
# LAST EDITED:	    05/13/2018
###

TGTS = bits
CFLAGS = -Wextra -pedantic -Wall -O3
CC = gcc

.PHONY: clean

$(TGTS):

clean:
	rm -f $(TGTS)

###############################################################################
