###############################################################################
# NAME:		    Makefile
#
# AUTHOR:	    Ethan D. Twardy
#
# DESCRIPTION:	    Makefile for index-test.c
#
# CREATED:	    11/02/2017
#
# LAST EDITED:	    12/27/2017
###

CC = gcc
CFLAGS = -g -Wall -O0

SRCS += index-test.c

OBJS = $(patsubst %.c,%.o,$(SRCS))

index-test: $(OBJS)

###############################################################################
