################################################################################
# NAME:		    Makefile
#
# AUTHOR:	    Ethan D. Twardy
#
# DESCRIPTION:	    Makefile for the project
#
# CREATED:	    11/28/2017
#
# LAST EDITED:	    11/28/2017
###

# TODO: Makefile

################################################################################
