#!/bin/sh
################################################################################
# NAME:		    payme
#
# AUTHOR:	    Ethan D. Twardy
#
# DESCRIPTION:	    This is the executable which calls ./pay.
#
# CREATED:	    11/28/2017
#
# LAST EDITED:	    11/29/2017
###

usage() {
    echo
    echo "Run with no args to trigger an interactive shell,"
    echo "or run with arguments for a nifty little one-liner."
    echo "audit\t\t- Run an audit, to see how much you've earned!"
    echo "costs\t\t- List all of your costs for the week."
    echo "reset\t\t- Reset the data (As in at the start of the week)."
    echo "spent\t\t- Add a new total to the total costs."
    echo "tasks [-a]\t- Print out the tasks that haven't been completed;"
    echo "\t\t(or all of the tasks)."
}

pay "$@" && usage

################################################################################
